import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { AuthProvider } from "@/providers/auth-provider";
import { CartProvider } from "@/providers/cart-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*
 * Display face for the wordmark, H1s, and the larger chrome text.
 * Space Grotesk is a strong grotesque with confident weights; it
 * sits next to Geist Sans without leaving the family, but its
 * tighter apertures and higher x-height give the brand chrome
 * (topbar wordmark, page H1s) the bolder "vibrant" voice the
 * product is moving toward. Body copy stays on Geist Sans.
 */
const display = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${display.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <QueryProvider>
        <AuthProvider>
          {/*
            CartProvider sits inside AuthProvider so it can be scoped
            to the authenticated app tree. Cart technically doesn't
            need auth, but it's meaningless without a logged-in
            customer, and this scope keeps the topbar's role check
            (user.role === "customer") honest.
          */}
          <CartProvider>
            {children}
            <Toaster />
          </CartProvider>
        </AuthProvider>
      </QueryProvider>
    </body>
    </html>
  );
}
